var res = {
"res@car.png":"res/car.png",
  "res@f1.jpg":"res/f1.jpg",
  "res@Layer_Btn.json":"res/Layer_Btn.json",
  "res@Layer_Cfg.json":"res/Layer_Cfg.json",
  "res@Layer_Charging.json":"res/Layer_Charging.json",
  "res@Layer_GameOver.json":"res/Layer_GameOver.json",
  "res@Layer_Guide_1.json":"res/Layer_Guide_1.json",
  "res@Layer_Guide_2.json":"res/Layer_Guide_2.json",
  "res@Layer_Header.json":"res/Layer_Header.json",
  "res@Layer_Over.json":"res/Layer_Over.json",
  "res@lighting.png":"res/lighting.png",
  "res@line_0.png":"res/line_0.png",
  "res@logo_200.png":"res/logo_200.png",
  "res@MainScene.json":"res/MainScene.json",
  "res@s0.png":"res/s0.png",
  "res@s1.png":"res/s1.png",
  "res@start-line.png":"res/start-line.png",
  "res@txtPanel.png":"res/txtPanel.png",
  "res@img@5-NEV-GTE.png":"res/img/5-NEV-GTE.png",
  "res@img@6-NEV-E.png":"res/img/6-NEV-E.png",
  "res@img@b1.png":"res/img/b1.png",
  "res@img@b2.png":"res/img/b2.png",
  "res@img@bba2.png":"res/img/bba2.png",
  "res@img@bbar.png":"res/img/bbar.png",
  "res@img@bbar1.png":"res/img/bbar1.png",
  "res@img@bg_t_1.png":"res/img/bg_t_1.png",
  "res@img@btn_n1.png":"res/img/btn_n1.png",
  "res@img@btn_reload.png":"res/img/btn_reload.png",
  "res@img@corver0.png":"res/img/corver0.png",
  "res@img@corver1.png":"res/img/corver1.png",
  "res@img@done.jpg":"res/img/done.jpg",
  "res@img@f1.jpg":"res/img/f1.jpg",
  "res@img@f2.jpg":"res/img/f2.jpg",
  "res@img@lighting.png":"res/img/lighting.png",
  "res@img@start-line.png":"res/img/start-line.png",
  "res@img@t2.png":"res/img/t2.png",
  "res@img@t_03.png":"res/img/t_03.png",
  "res@img@t_03_1.png":"res/img/t_03_1.png",
  "res@img@t_03_2.png":"res/img/t_03_2.png",
  "res@img@t_04.png":"res/img/t_04.png",
  "res@Default@Button_Disable.png":"res/Default/Button_Disable.png",
  "res@Default@Button_Normal.png":"res/Default/Button_Normal.png",
  "res@Default@Button_Press.png":"res/Default/Button_Press.png",
  "res@Default@CheckBoxNode_Disable.png":"res/Default/CheckBoxNode_Disable.png",
  "res@Default@CheckBoxNode_Normal.png":"res/Default/CheckBoxNode_Normal.png",
  "res@Default@CheckBox_Disable.png":"res/Default/CheckBox_Disable.png",
  "res@Default@CheckBox_Normal.png":"res/Default/CheckBox_Normal.png",
  "res@Default@CheckBox_Press.png":"res/Default/CheckBox_Press.png",
  "res@Default@ImageFile.png":"res/Default/ImageFile.png",
  "res@Default@LoadingBarFile.png":"res/Default/LoadingBarFile.png",
  "res@Default@Sprite.png":"res/Default/Sprite.png",
  "res@cover@car.png":"res/cover/car.png",
  "res@cover@e.png":"res/cover/e.png",
  "res@cover@line_1.png":"res/cover/line_1.png",
  "res@cover@line_2.png":"res/cover/line_2.png",
  "res@cover@oil.png":"res/cover/oil.png",
  "res@city_1@2@bg.jpg":"res/city_1/2/bg.jpg",
  "res@city_1@2@bg_all.jpg":"res/city_1/2/bg_all.jpg",
  "res@city_1@2@panel@0.png":"res/city_1/2/panel/0.png",
  "res@city_1@2@panel@1.png":"res/city_1/2/panel/1.png",
  "res@city_1@2@panel@10.png":"res/city_1/2/panel/10.png",
  "res@city_1@2@panel@2.png":"res/city_1/2/panel/2.png",
  "res@city_1@2@panel@3.png":"res/city_1/2/panel/3.png",
  "res@city_1@2@panel@4.png":"res/city_1/2/panel/4.png",
  "res@city_1@2@panel@5.png":"res/city_1/2/panel/5.png",
  "res@city_1@2@panel@6.png":"res/city_1/2/panel/6.png",
  "res@city_1@2@panel@7.png":"res/city_1/2/panel/7.png",
  "res@city_1@2@panel@8.png":"res/city_1/2/panel/8.png",
  "res@city_1@2@panel@9.png":"res/city_1/2/panel/9.png",
  "res@city_1@1@bg.jpg":"res/city_1/1/bg.jpg",
  "res@city_1@1@bg_all.jpg":"res/city_1/1/bg_all.jpg",
  "res@city_1@1@panel@0.png":"res/city_1/1/panel/0.png",
  "res@city_1@1@panel@1.png":"res/city_1/1/panel/1.png",
  "res@city_1@1@panel@10.png":"res/city_1/1/panel/10.png",
  "res@city_1@1@panel@2.png":"res/city_1/1/panel/2.png",
  "res@city_1@1@panel@3.png":"res/city_1/1/panel/3.png",
  "res@city_1@1@panel@4.png":"res/city_1/1/panel/4.png",
  "res@city_1@1@panel@5.png":"res/city_1/1/panel/5.png",
  "res@city_1@1@panel@6.png":"res/city_1/1/panel/6.png",
  "res@city_1@1@panel@7.png":"res/city_1/1/panel/7.png",
  "res@city_1@1@panel@8.png":"res/city_1/1/panel/8.png",
  "res@city_1@1@panel@9.png":"res/city_1/1/panel/9.png",
  "res@city_1@0@bg.jpg":"res/city_1/0/bg.jpg",
  "res@city_1@0@bg_all.jpg":"res/city_1/0/bg_all.jpg",
  "res@city_1@0@panel@0.png":"res/city_1/0/panel/0.png",
  "res@city_1@0@panel@1.png":"res/city_1/0/panel/1.png",
  "res@city_1@0@panel@10.png":"res/city_1/0/panel/10.png",
  "res@city_1@0@panel@2.png":"res/city_1/0/panel/2.png",
  "res@city_1@0@panel@3.png":"res/city_1/0/panel/3.png",
  "res@city_1@0@panel@4.png":"res/city_1/0/panel/4.png",
  "res@city_1@0@panel@5.png":"res/city_1/0/panel/5.png",
  "res@city_1@0@panel@6.png":"res/city_1/0/panel/6.png",
  "res@city_1@0@panel@7.png":"res/city_1/0/panel/7.png",
  "res@city_1@0@panel@8.png":"res/city_1/0/panel/8.png",
  "res@city_1@0@panel@9.png":"res/city_1/0/panel/9.png",
  "res@city_0@2@bg.jpg":"res/city_0/2/bg.jpg",
  "res@city_0@2@bg_all.jpg":"res/city_0/2/bg_all.jpg",
  "res@city_0@2@panel@0.png":"res/city_0/2/panel/0.png",
  "res@city_0@2@panel@1.png":"res/city_0/2/panel/1.png",
  "res@city_0@2@panel@10.png":"res/city_0/2/panel/10.png",
  "res@city_0@2@panel@2.png":"res/city_0/2/panel/2.png",
  "res@city_0@2@panel@3.png":"res/city_0/2/panel/3.png",
  "res@city_0@2@panel@4.png":"res/city_0/2/panel/4.png",
  "res@city_0@2@panel@5.png":"res/city_0/2/panel/5.png",
  "res@city_0@2@panel@6.png":"res/city_0/2/panel/6.png",
  "res@city_0@2@panel@7.png":"res/city_0/2/panel/7.png",
  "res@city_0@2@panel@8.png":"res/city_0/2/panel/8.png",
  "res@city_0@2@panel@9.png":"res/city_0/2/panel/9.png",
  "res@city_0@1@bg.jpg":"res/city_0/1/bg.jpg",
  "res@city_0@1@bg_all.jpg":"res/city_0/1/bg_all.jpg",
  "res@city_0@1@panel@0.png":"res/city_0/1/panel/0.png",
  "res@city_0@1@panel@1.png":"res/city_0/1/panel/1.png",
  "res@city_0@1@panel@10.png":"res/city_0/1/panel/10.png",
  "res@city_0@1@panel@2.png":"res/city_0/1/panel/2.png",
  "res@city_0@1@panel@3.png":"res/city_0/1/panel/3.png",
  "res@city_0@1@panel@4.png":"res/city_0/1/panel/4.png",
  "res@city_0@1@panel@5.png":"res/city_0/1/panel/5.png",
  "res@city_0@1@panel@6.png":"res/city_0/1/panel/6.png",
  "res@city_0@1@panel@7.png":"res/city_0/1/panel/7.png",
  "res@city_0@1@panel@8.png":"res/city_0/1/panel/8.png",
  "res@city_0@1@panel@9.png":"res/city_0/1/panel/9.png",
  "res@city_0@0@bg.jpg":"res/city_0/0/bg.jpg",
  "res@city_0@0@bg_all.jpg":"res/city_0/0/bg_all.jpg",
  "res@city_0@0@panel@0.png":"res/city_0/0/panel/0.png",
  "res@city_0@0@panel@1.png":"res/city_0/0/panel/1.png",
  "res@city_0@0@panel@10.png":"res/city_0/0/panel/10.png",
  "res@city_0@0@panel@2.png":"res/city_0/0/panel/2.png",
  "res@city_0@0@panel@3.png":"res/city_0/0/panel/3.png",
  "res@city_0@0@panel@4.png":"res/city_0/0/panel/4.png",
  "res@city_0@0@panel@5.png":"res/city_0/0/panel/5.png",
  "res@city_0@0@panel@6.png":"res/city_0/0/panel/6.png",
  "res@city_0@0@panel@7.png":"res/city_0/0/panel/7.png",
  "res@city_0@0@panel@8.png":"res/city_0/0/panel/8.png",
  "res@city_0@0@panel@9.png":"res/city_0/0/panel/9.png"
  
};


var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}


//var res1 = {
//    "res@Audio@bg.mp3": "res/Audio/bg.mp3",
//    "res@Audio@engine_ele.mp3": "res/Audio/engine_ele.mp3",
//    "res@Audio@engine_gas.mp3": "res/Audio/engine_gas.mp3"
//};

//var g_resources1 = [];
//for (var i in res1) {
//    g_resources1.push(res1[i]);
//}


